stages:
  - test

test36:
  image: python:3.6
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install HTSeq
    - pip install .
    - pip install nose2
    - nose2 -v


test37:
  image: python:3.7
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install HTSeq
    - pip install .
    - pip install nose2
    - nose2 -v

test38:
  image: python:3.8
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install HTSeq
    - pip install .
    - pip install nose2
    - nose2 -v

test39:
  image: python:3.9
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install HTSeq
    - pip install .
    - pip install nose2
    - nose2 -v
