stages:
  - build
  - test

build:
  image: python:3.7
  stage: build
  script:
    - pip install -r requirements.txt
    - pip install HTSeq
    - pip install .

test:
  image: python:3.7
  stage: test
  script:
    - pip install nose2
    - nose2 -v
